node:
  bn: True
  checkpoint: computers_node
  decoder_channels: 64
  decoder_dropout: 0.2
  encoder_channels: 256
  encoder_dropout: 0.5
  encoder_layers: 2
  epochs: 1000
  eval_period: 10
  l2_norm: False
  lr: 0.001
  runs: 10
  temp: 0.6
  weight_decay: 0
  weight_decay_prob: 5e-4

link:
  bn: True
  checkpoint: computers_link
  decoder_channels: 64
  decoder_dropout: 0.2
  encoder_channels: 256
  encoder_dropout: 0.5
  encoder_layers: 3
  epochs: 1000
  eval_period: 10
  lr: 0.001
  runs: 10
  temp: 0.6
  weight_decay: 1e-4