node:
  bn: True
  checkpoint: pubmed_node
  decoder_channels: 32
  decoder_dropout: 0.7
  encoder_channels: 64
  encoder_dropout: 0.6
  encoder_layers: 2
  epochs: 1000
  eval_period: 10
  l2_norm: True
  lr: 0.001
  runs: 10
  temp: 0.2
  weight_decay: 5e-5
  weight_decay_prob: 5e-5

link:
  bn: True
  checkpoint: pubmed_link
  decoder_channels: 64
  decoder_dropout: 0.2
  encoder_channels: 256
  encoder_dropout: 0.8
  encoder_layers: 2
  epochs: 1000
  eval_period: 10
  lr: 0.01
  runs: 10
  temp: 1
  weight_decay: 5e-4